function Hd = filter_notch_60
%FILTER_NOTCH_60 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 06-Oct-2023 23:12:18

% Elliptic Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 160;  % Sampling Frequency

N      = 8;     % Order
Fpass1 = 59.5;  % First Passband Frequency
Fpass2 = 60.5;  % Second Passband Frequency
Apass  = 1;     % Passband Ripple (dB)
Astop  = 80;    % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandstop('N,Fp1,Fp2,Ap,Ast', N, Fpass1, Fpass2, Apass, ...
                      Astop, Fs);
Hd = design(h, 'ellip');

% [EOF]

